#!/bin/bash
set -e
set -x 

JOB_NAME="tomcat"
BASE_NAME="autoscaler_server"
RUN_DIR=/var/vcap/sys/run/$JOB_NAME
LOG_DIR=/var/vcap/sys/log/$JOB_NAME
PIDFILE=${RUN_DIR}/$JOB_NAME.pid
source /var/vcap/packages/pid_utils/pid_utils.sh

export JAVA_HOME=/var/vcap/packages/java/jdk
export CATALINA_PID=$PIDFILE

case $1 in

  start)
    pid_guard $PIDFILE $JOB_NAME
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    #config autoscaler server
    host="<%= p("autoscaler.couchdb.host") %>";
    sed -i "s@couchdbHost=.*@couchdbHost=${host}@" /var/vcap/packages/${BASE_NAME}/server/WEB-INF/classes/config.properties
    cp -r /var/vcap/packages/${BASE_NAME}/server /var/vcap/packages/tomcat/webapps

    #config server.xml
    cp /var/vcap/jobs/${BASE_NAME}/conf/server.xml /var/vcap/packages/tomcat/conf/server.xml

    exec /var/vcap/packages/tomcat/bin/catalina.sh start  > $LOG_DIR/tomcat.stdout.log 2> $LOG_DIR/$tomcat.stderr.log 
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  *)
  echo "Usage: tomcat_ctl {start|stop}" ;;
esac
exit 0
